import {escape as e, textLink, paperLink, tags, label, profiles, portrait, researchDiagram, trajectory, paperReference, publication, featured, pageHero, authors} from './components.mjs';

const cvProgram = p => `<article class="program-row" id="${e(p.id)}"><div class="program-meta"><span>${e(p.period)}</span><span>${p.period.includes('present')?'Ongoing':'Completed'}</span></div><div><h3>${e(p.englishTitle)}</h3><p class="original-title" lang="ko">${e(p.title)}</p><p>${e(p.sponsor)}</p>${p.personalRole?`<p class="program-role">Role: ${e(p.personalRole)}</p>`:''}</div></article>`;
const caseStudy = (d,p,extra='') => `<article class="project-detail" id="${e(p.id)}"><div class="project-heading"><p class="project-state">${e(p.status)}</p><h3>${e(p.title)}</h3>${extra}</div><div class="project-body"><p class="research-question">${e(p.question)}</p><dl class="project-facts"><div><dt>Role</dt><dd>${e(p.role)}</dd></div><div><dt>Scientific approach</dt><dd>${e(p.approach)}</dd></div><div><dt>${p.papers.length?'Key finding':'Current status'}</dt><dd>${e(p.outcome)}</dd></div></dl><p class="project-methods">Methods: ${e(p.methods.join(' · '))}</p>${p.papers.length?`<h4 class="small-heading">Related publications</h4><ul class="paper-references">${p.papers.map(id=>paperReference(d,id)).join('')}</ul>`:''}${p.patents.length?`<h4 class="small-heading">Related patents</h4><ul class="paper-references">${p.patents.map(i=>`<li><a href="patents.html#${e(d.patents[i].id)}">${e(d.patents[i].englishTitle)}</a><span>${e(d.patents[i].status)} · ${e(d.patents[i].number)}</span></li>`).join('')}</ul>`:''}</div></article>`;

export function home(d) {
  const previews=[
    {id:'doctoral-ionic-memory',category:'Independent doctoral research',description:'State formation and low-frequency noise in ion-migration-controlled multilevel memristors.',anchor:'ionic-dynamics'},
    {id:'flexible-fpcb',category:'Industry–academic R&D',description:''},
    {id:'photonic-skin',category:'Government-funded R&D',description:''}
  ];
  return `<section class="home-hero shell"><div class="home-hero-grid"><div class="home-hero-copy"><p class="home-name">${e(d.profile.name.toUpperCase())}</p><h1>Interface &amp; device physics<br>for emerging electronics.</h1><p class="home-deck">I study how molecular and thin-film interfaces, defects, ionic motion, and charge transport shape memory, optoelectronic, and flexible electronic devices.</p><dl class="hero-focus"><div><dt>Current focus</dt><dd>Emerging memory · Device reliability</dd></div><div><dt>Long-term direction</dt><dd>Integrated electronic systems</dd></div></dl><p class="home-affiliation">Integrated M.S.–Ph.D. researcher · Electrical Engineering, Korea University</p><div class="home-actions"><a class="text-link" href="research.html">Research <span aria-hidden="true">→</span></a><a class="text-link" href="#featured">Selected work <span aria-hidden="true">→</span></a><a class="text-link" href="${e(d.profile.cv)}" download>CV <span aria-hidden="true">↓</span></a></div></div>${portrait(d)}</div></section>
  <section class="home-research shell" id="research" aria-labelledby="home-research-title"><div class="home-section-head"><h2 id="home-research-title">Research</h2>${textLink('research.html','Research in depth')}</div><div class="home-core"><span>Core science</span><h3>Interfaces · Defects · Ions · Transport</h3><p>One physical framework, explored across multiple electronic-device platforms.</p></div><div class="home-platforms"><a href="research.html#memory"><h3>Memory &amp; reliability</h3><p>Memristive switching, state variability, and capacitive-device questions.</p></a><a href="research.html#optoelectronics"><h3>Optoelectronics &amp; hybrid devices</h3><p>Molecular contacts, photovoltaic devices, and photodetectors.</p></a><a href="research.html#flexible"><h3>Flexible &amp; stretchable electronics</h3><p>Interconnects, stretchable PCBs, and thin films in government and industry R&amp;D.</p></a></div><div class="home-future"><span>Long-term direction</span><p>Integrated electronic systems</p><small>Low-temperature electronics · Heterogeneous integration · 3D integration · Device–system co-design</small></div></section>
  <section class="home-featured" id="featured" aria-labelledby="featured-title"><div class="shell"><div class="home-section-head"><h2 id="featured-title">Featured work</h2>${textLink('publications.html','All publications')}</div>${featured(d)}</div></section>
  <section class="home-current shell" aria-labelledby="current-title"><div class="home-section-head"><h2 id="current-title">Current research</h2>${textLink('projects.html','View all projects')}</div><div class="current-list">${previews.map(item=>{const p=d.projects.find(project=>project.id===item.id);return `<article class="current-row"><div><p class="current-category">${e(item.category)}</p><h3>${e(p.englishTitle)}</h3></div><div>${item.description?`<p>${e(item.description)}</p>`:''}<p class="current-meta">${e(p.period)} · Ongoing<br>${e(p.sponsor)}${p.personalRole?`<br>Role: ${e(p.personalRole)}`:''}</p>${textLink(`projects.html#${e(item.anchor??p.id)}`,'View project')}</div></article>`}).join('')}</div></section>
  <section class="home-about shell" aria-labelledby="home-about-title"><h2 id="home-about-title">About</h2><div><p>Min Jong Lee is an integrated M.S.–Ph.D. researcher in electrical engineering at Korea University. His first-author work connects molecular interfaces, optoelectronic devices, and emerging memory.</p>${textLink('about.html','More about Min Jong Lee')}</div></section>`;
}

export function research(d) {
  const core=d.pillars.find(p=>p.id==='interfaces');
  const memory=d.pillars.find(p=>p.id==='memory');
  const future=d.pillars.find(p=>p.id==='integration');
  return `${pageHero('Research','From interfaces to integrated electronic systems.','I study how local structure, defects, mobile ions, and charge transport affect electronic-device behavior across several platforms.')}<div class="shell research-map-wrap">${researchDiagram()}</div>
  <section class="section shell research-area" id="interfaces"><div class="research-area-heading"><p class="area-type">Core physics</p><h2>Interfaces · Defects · Ions · Transport</h2></div><div class="research-area-body"><h3>${e(core.question)}</h3><p>${e(core.motivation)}</p><p><strong>Published foundation.</strong> ${e(core.results)}</p><p><strong>Methods.</strong> ${e(core.methods.join(' · '))}</p><div class="research-actions">${textLink('publications.html','Relevant publications')}</div></div></section>
  <section class="section shell research-area" id="memory"><div class="research-area-heading"><p class="area-type">Device platform</p><h2>Memory &amp; reliability</h2></div><div class="research-area-body"><h3>${e(memory.question)}</h3><p>${e(memory.motivation)}</p><p><strong>Published work.</strong> ${e(memory.results)}</p><p><strong>Current research.</strong> ${e(memory.current)}</p><p><strong>Methods.</strong> ${e(memory.methods.join(' · '))}</p><h4 class="small-heading">Selected papers</h4><ul class="paper-references">${memory.papers.slice(0,2).map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#ionic-dynamics','Related project')}</div></div></section>
  <section class="section shell research-area" id="optoelectronics"><div class="research-area-heading"><p class="area-type">Device platform</p><h2>Optoelectronics &amp; hybrid devices</h2></div><div class="research-area-body"><h3>How do contacts and traps shape light conversion and detection?</h3><p>Organic and hybrid devices provide a continuing platform for examining molecular contacts, thin-film electrodes, and charge-selective interfaces.</p><p><strong>Published work.</strong> First-author papers address self-assembled contacts and ALD oxide electrodes; collaborative work includes photodetectors and hybrid materials.</p><p><strong>Methods.</strong> Self-assembled monolayers · thin-film interfaces · organic photovoltaics · photodetectors.</p><h4 class="small-heading">Selected papers</h4><ul class="paper-references">${d.connected.papers.slice(0,2).map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#molecular-contacts','Related project')}</div></div></section>
  <section class="section shell research-area" id="flexible"><div class="research-area-heading"><p class="area-type">Device platform</p><h2>Flexible &amp; stretchable electronics</h2></div><div class="research-area-body"><h3>${e(d.flexible.question)}</h3><p>${e(d.flexible.scope)}</p><p>These programs bring mechanical deformation into the same materials-to-device questions of transport and reliability.</p><div class="research-actions">${textLink('projects.html#flexible-fpcb','Flexible interconnects')}${textLink('projects.html#stretchable-pcb','Stretchable PCBs')}</div></div></section>
  <section class="section shell research-area research-emerging" id="integration"><div class="research-area-heading"><p class="area-type">Long-term research direction</p><h2>Integrated electronic systems</h2></div><div class="research-area-body"><h3>${e(future.question)}</h3><p><strong>Existing foundation.</strong> ${e(future.current)}</p><p><strong>Possible directions.</strong> Low-temperature oxide electronics, heterogeneous and 3D integration, device–system co-design, and integrated memory, sensing, and optoelectronics.</p><div class="research-actions">${textLink('projects.html#ald-electrodes-industry','Related program')}${textLink('publications.html#paper-06','Foundation paper')}</div></div></section>`;
}

export function publications(d) {
  const published=d.publications.filter(p=>!p.status).sort((a,b)=>b.year-a.year||(a.type==='first'?0:1)-(b.type==='first'?0:1));
  const years=[...new Set(published.map(p=>p.year))];
  const manuscripts=d.publications.filter(p=>p.status);
  const selected=[...d.featured.slice(0,3),{paper:'paper-06',title:'ALD oxide electrodes across device classes',contribution:'Laminated In₂O₃:V₂O₅ electrodes were studied in organic photovoltaics and capacitor devices.'}];
  return `${pageHero('Publications','Publications.','Selected research contributions followed by the complete publication record, organized by year.',`<div class="link-row">${textLink(d.scholar,'Google Scholar')}<button type="button" class="text-link print-button" hidden>Print publication list <span aria-hidden="true">↗</span></button></div>`)}
  <section class="section shell selected-publications" aria-labelledby="selected-publications-title"><h2 id="selected-publications-title">Selected publications</h2><div class="selected-publication-list">${selected.map(item=>{const p=d.publications.find(x=>x.id===item.paper);return `<article class="selected-publication ${p.image?'selected-with-image':''}">${p.image?`<figure class="selected-figure"><img src="${e(p.image)}" alt="${e(p.imageAlt)}" width="960" height="600" loading="lazy" decoding="async"></figure>`:`<p class="work-source">${e(p.journal.split(' · ')[0])} · ${p.year}</p>`}<div>${p.image?`<p class="work-source">${e(p.journal.split(' · ')[0])} · ${p.year}</p>`:''}<h3>${e(item.title)}</h3><p>${e(item.contribution)}</p><p class="work-paper">${e(p.title)}</p>${paperLink(p)}</div></article>`}).join('')}</div></section>
  <section class="section shell publications-section" id="publications"><div class="section-heading"><div><h2>Full publication list</h2><p class="publication-section-note">Chronological by year · first-author work identified in each entry</p></div></div><div class="publication-controls" role="group" aria-label="Filter publications by research topic" hidden><button class="filter-button active" type="button" data-filter="all" aria-pressed="true">All</button>${d.topics.map(t=>`<button class="filter-button" type="button" data-filter="${t.id}" aria-pressed="false">${e(t.label)}</button>`).join('')}</div><div class="publication-intro"><p id="publication-count" role="status" aria-live="polite">${published.length} published papers</p></div><div id="publication-list">${years.map(year=>`<section class="publication-year" data-year-group><h3>${year}</h3>${published.filter(p=>p.year===year).map(p=>publication(d,p,{showYear:false})).join('')}</section>`).join('')}</div><p id="publication-empty" class="publication-empty" hidden>No published paper is assigned to this topic. Related programs appear on <a href="projects.html#flexible-fpcb">Projects</a>.</p><p class="record-note">${e(d.notes.authors)}</p><section class="manuscripts" aria-labelledby="manuscripts-title"><div class="section-heading"><div>${label('Work in progress')}<h2 id="manuscripts-title">Manuscripts</h2></div></div>${manuscripts.map(p=>publication(d,p)).join('')}<p class="record-note">A manuscript in revision is distinct from an accepted or published article.</p></section><p class="record-note">${e(d.notes.bibliography)} DOI links are provided where verified; other records link to an explicitly labeled Scholar search.</p></section>`;
}

export function projects(d) {
  const byCategory=category=>d.projects.filter(p=>p.category===category);
  const independent=d.projects.find(p=>p.id==='doctoral-ionic-memory');
  const doctoral=d.researchProjects.find(p=>p.id==='ionic-dynamics');
  const publishedCases=d.researchProjects.filter(p=>p.id!=='ionic-dynamics');
  return `${pageHero('Projects','Research programs &amp; published work.','Independent doctoral research, participation in funded R&D programs, and selected published studies.')}
  <section class="section shell project-group" id="independent"><div class="project-group-heading"><h2>01 · Independent research</h2><p>Doctoral Research Support Program · Ministry of Education · ${e(independent.period)}</p></div>${caseStudy(d,doctoral,`<p class="original-title" lang="ko">${e(independent.title)}</p>`)}</section>
  <section class="section shell project-group" id="government"><div class="project-group-heading"><h2>02 · Government-funded R&amp;D programs</h2><p>Participation across flexible electronics, sensing, displays, and photovoltaics.</p></div><div class="program-list">${byCategory('government').map(cvProgram).join('')}</div></section>
  <section class="section shell project-group" id="industry"><div class="project-group-heading"><h2>03 · Industry–academic R&amp;D programs</h2><p>Materials and device work with Samsung Electronics.</p></div><div class="program-list">${byCategory('industry').map(cvProgram).join('')}</div></section>
  <section class="section shell project-group" id="published"><div class="project-group-heading"><h2>04 · Selected published research</h2><p>Scientific questions and findings linked to first-author publications.</p></div>${publishedCases.map(p=>caseStudy(d,p)).join('')}</section><p class="record-note shell projects-note">English project labels are descriptive translations of the original Korean titles.</p>`;
}

export function patents(d) {
  return `${pageHero('Intellectual property','Patents &amp; technology translation.','Registered patents and applications connected to electronic materials and devices.')}<section class="section shell patent-section"><div class="section-intro"><p>Each record lists its legal status, jurisdiction, inventors, and identifier. Related research links indicate a topic connection.</p></div><div class="patent-list">${d.patents.map((p,i)=>`<article class="patent-item" id="${e(p.id)}"><div class="patent-number">${String(i+1).padStart(2,'0')}<span class="badge ${p.status==='Registered'?'':'badge-outline'}">${e(p.status)}</span></div><div><h2>${e(p.englishTitle)}</h2><p class="original-title" ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</p><dl class="patent-facts"><div><dt>Inventors</dt><dd lang="ko">${e(p.inventors)}</dd></div><div><dt>Jurisdiction</dt><dd>${e(p.jurisdiction)}</dd></div><div><dt>${p.status==='Registered'?'Registration number':'Application number'}</dt><dd>${e(p.number)}</dd></div><div><dt>${p.status==='Registered'?'Registration date':'Filing date'}</dt><dd>${e(p.date)}</dd></div><div><dt>Technology area</dt><dd>${e(p.tags.map(x=>x.toLowerCase()).join(' · '))}</dd></div></dl>${p.territoryNote?`<p class="record-note">${e(p.territoryNote)}</p>`:''}${textLink('research.html#'+p.relatedResearch,'Related research')}</div></article>`).join('')}</div></section>`;
}

export function about(d) {
  const education=d.profile.education.map(item=>`<div class="education-entry"><p class="education-period">${e(item.period)}</p><p><strong>${e(item.degree)}</strong><br>${e(item.school)}</p><p class="education-meta">GPA: ${e(item.gpa)}${item.honor?` · ${e(item.honor)}`:''}${item.advisor?`<br>Advisor: ${e(item.advisor)}`:''}</p></div>`).join('');
  return `<section class="about-intro shell"><div class="about-intro-copy"><h1>${e(d.profile.name)}</h1><p class="about-field">Electronic Devices · Materials · Interface Physics</p><p class="about-position">Integrated M.S.–Ph.D. Researcher<br>School of Electrical Engineering<br>Korea University</p>${profiles(d)}</div>${portrait(d)}</section>
  <section class="section shell about-narrative"><div><h2>Biography</h2></div><div><p>${e(d.profile.bio)}</p><p>My research experience also includes flexible interconnects, stretchable PCB technologies, and durable thin-film systems through government-funded and industry–academic R&amp;D programs.</p></div></section>
  <section class="section shell about-narrative"><div><h2>Research focus</h2></div><div><p>${e(d.profile.vision)}</p>${textLink('research.html','Explore research')}</div></section>
  <section class="section shell about-journey"><h2>Research journey</h2><p class="section-intro">Organic and hybrid devices led to molecular interfaces, defect and ionic physics, and emerging memory. Flexible-device programs broaden this work; integrated systems form a long-term direction.</p>${trajectory(d)}</section>
  <section class="section shell about-context"><div><h2>Current research environment</h2><p>${e(d.profile.lab)}<br>${e(d.profile.institution)}<br>Advisor: <a href="${e(d.profile.advisorUrl)}">${e(d.profile.advisor)}</a></p><p class="about-independence">Principal Investigator, Doctoral Research Support Program · Ministry of Education · since September 2026</p>${textLink('projects.html#independent','Independent research')}${textLink(d.profile.labUrl,'Visit AEEL')}</div><div><h2>Education</h2>${education}</div></section>${activities(d)}`;
}

export function activities(d) {
  const list=category=>d.awards.filter(a=>a.category===category).sort((a,b)=>b.year-a.year).map(a=>`<article class="activity-row"><span class="period">${a.year}</span><div><h3>${e(a.englishTitle)}</h3><p lang="ko">${e(a.title)}</p></div></article>`).join('');
  return `<section class="section shell about-recognition" id="recognition"><h2>Selected awards &amp; recognition</h2><div class="activity-list">${list('award')}</div><h3 class="recognition-subhead">Scholarships &amp; researcher programs</h3><div class="activity-list">${list('fellowship')}</div></section>${d.gallery.some(g=>g.image)?`<section class="section shell about-gallery" id="gallery"><h2>Research / conference gallery</h2><div class="gallery-grid">${d.gallery.filter(g=>g.image).map(g=>`<figure><div class="gallery-image"><img src="${e(g.image)}" alt="${e(g.alt)}" width="900" height="675" loading="lazy" decoding="async"></div><figcaption><h3>${e(g.title)}</h3><p>${e(g.caption)}</p></figcaption></figure>`).join('')}</div></section>`:''}`;
}

export function cv(d) {
  const pubs=d.publications.filter(p=>!p.status).sort((a,b)=>b.year-a.year);
  const education=d.profile.education.map(item=>`<p><strong>${e(item.degree)}</strong> · ${e(item.period)}<br>${e(item.school)}<br>GPA: ${e(item.gpa)}${item.honor?` · ${e(item.honor)}`:''}${item.advisor?`<br>Advisor: ${e(item.advisor)}`:''}</p>`).join('');
  return `<div class="shell cv-toolbar">${textLink(d.profile.cv,'Download CV (PDF)','download')}<button class="text-link print-button" type="button" hidden>Print CV <span aria-hidden="true">↗</span></button><span>Public version · Updated ${e(d.profile.updated)}</span></div><article class="cv-document shell"><header><p class="eyebrow">Curriculum vitae</p><h1>Min Jong Lee</h1><p>School of Electrical Engineering, Korea University<br>Seoul, Republic of Korea · <a href="mailto:${e(d.profile.email)}">${e(d.profile.email)}</a><br><a href="https://minjonglee.github.io/">minjonglee.github.io</a> · <a href="${e(d.scholar)}">Google Scholar</a></p></header><section><h2>Research identity</h2><p>Interface and device physics for emerging electronics</p><p>Research interests: molecular and thin-film interfaces, defects, ionic dynamics, charge transport, emerging memory, optoelectronics, and flexible-device R&amp;D. Integrated electronic systems are a long-term research direction.</p></section><section><h2>Education</h2>${education}</section><section><h2>Publications</h2><ol class="cv-publications">${pubs.map(p=>`<li><p>${authors(p.authors)}. “${e(p.title)}.” <em>${e(p.journal)}</em> (${p.year}).${p.type==='first'?' <strong>[First author]</strong>':''}${p.doi?` <a href="https://doi.org/${e(p.doi)}">doi:${e(p.doi)}</a>`:''}</p></li>`).join('')}</ol></section><section><h2>Manuscript in revision</h2>${d.publications.filter(p=>p.status).map(p=>`<p>${authors(p.authors)}. “${e(p.title)}.” ${e(p.journal)} (${p.year}). <strong>${e(p.status)}; not published.</strong></p>`).join('')}</section><section><h2>Patents</h2><ol>${d.patents.map(p=>`<li><p><span lang="ko">${e(p.inventors)}</span>. “<span ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</span>.” ${e(p.status)} · ${e(p.jurisdiction)} · ${e(p.number)} · ${e(p.date)}.${p.territoryNote?' '+e(p.territoryNote):''}</p></li>`).join('')}</ol></section><section><h2>Research projects</h2>${d.projects.map(p=>`<div class="cv-entry"><p><strong>${e(p.englishTitle)}</strong><br><span lang="ko">${e(p.title)}</span><br>${e(p.sponsor)} · ${e(p.period)} · ${e(p.personalRole)}</p></div>`).join('')}</section><section><h2>Awards &amp; academic programs</h2>${d.awards.map(a=>`<div class="cv-entry"><p><strong>${a.year} · ${e(a.englishTitle)}</strong><br><span lang="ko">${e(a.title)}</span></p></div>`).join('')}</section><p class="cv-source">† Equal contribution; * Corresponding author. The public version omits a phone number and detailed postal address.</p></article>`;
}
