import {escape as e, textLink, tags, label, profiles, portrait, researchDiagram, trajectory, paperReference, publication, featured, pageHero, authors} from './components.mjs';

const cvProgram = p => `<article class="program-row" id="${e(p.id)}"><div class="program-meta"><span>${e(p.period)}</span><span>${p.period.includes('present')?'Ongoing':'Completed'}</span></div><div><h3>${e(p.englishTitle)}</h3><p class="original-title" lang="ko">${e(p.title)}</p><p>${e(p.sponsor)}</p><p class="program-role">Individual role: ${p.personalRole?e(p.personalRole):'<span class="verify">[VERIFY ROLE]</span>'}</p></div></article>`;
const caseStudy = (d,p,extra='') => `<article class="project-detail" id="${e(p.id)}"><div class="project-heading"><p class="project-state">${e(p.status)}</p><h3>${e(p.title)}</h3>${extra}</div><div class="project-body"><p class="research-question">${e(p.question)}</p><dl class="project-facts"><div><dt>Role</dt><dd>${e(p.role)}</dd></div><div><dt>Approach</dt><dd>${e(p.approach)}</dd></div><div><dt>${p.papers.length?'Verified output':'Status'}</dt><dd>${e(p.outcome)}</dd></div></dl>${tags(p.methods)}${p.papers.length?`<h4 class="small-heading">Related papers</h4><ul class="paper-references">${p.papers.map(id=>paperReference(d,id)).join('')}</ul>`:''}${p.patents.length?`<h4 class="small-heading">Related patents</h4><ul class="paper-references">${p.patents.map(i=>`<li><a href="patents.html#${e(d.patents[i].id)}">${e(d.patents[i].englishTitle)}</a><span>${e(d.patents[i].status)} · ${e(d.patents[i].number)}</span></li>`).join('')}</ul>`:''}</div></article>`;

export function home(d) {
  const published=d.publications.filter(p=>!p.status);
  const firstAuthor=published.filter(p=>p.type==='first');
  const registered=d.patents.filter(p=>p.status==='Registered');
  const previews=[
    {id:'doctoral-ionic-memory',category:'Independent doctoral research',description:'State formation and low-frequency noise in ion-migration-controlled multilevel memristors.',anchor:'ionic-dynamics'},
    {id:'flexible-fpcb',category:'Industry collaboration',description:'CV-listed work on interconnect materials for highly flexible FPCBs.'},
    {id:'photonic-skin',category:'Interdisciplinary program',description:'CV-listed work on photonic skin for ultralight aerial Physical AI.'}
  ];
  return `<section class="home-hero shell"><div class="home-hero-grid"><div class="home-hero-copy"><p class="home-name">${e(d.profile.name.toUpperCase())}</p><h1>Interface &amp; device physics<br>for emerging electronics.</h1><p class="home-deck">I study how molecular and thin-film interfaces, defects, ionic motion, and charge transport govern electronic devices. Published work spans memory and optoelectronics; CV-listed collaborations extend to flexible electronics.</p><dl class="hero-focus"><div><dt>Current focus</dt><dd>Emerging memory · Device reliability</dd></div><div><dt>Future direction</dt><dd>Integrated &amp; 3D electronics</dd></div></dl><p class="home-affiliation">Korea University · Electrical Engineering</p><div class="home-actions"><a class="text-link" href="research.html">Research <span aria-hidden="true">→</span></a><a class="text-link" href="#featured">Selected work <span aria-hidden="true">→</span></a><a class="text-link" href="${e(d.profile.cv)}" download>CV <span aria-hidden="true">↓</span></a></div></div>${portrait(d)}</div></section>
  <section class="home-highlights shell" aria-labelledby="highlights-title"><div class="home-section-head"><h2 id="highlights-title">Selected highlights</h2></div><div class="highlight-grid"><a href="publications.html"><strong>${published.length}</strong><span>Published papers</span></a><a href="publications.html"><strong>${firstAuthor.length}</strong><span>First-author papers</span></a><a href="patents.html"><strong>${registered.length}</strong><span>Registered patents</span></a></div><p class="highlight-source">CV record updated ${e(d.profile.updated)}.</p></section>
  <section class="home-research shell" id="research" aria-labelledby="home-research-title"><div class="home-section-head"><h2 id="home-research-title">Research</h2>${textLink('research.html','Research in depth')}</div><div class="home-core"><span>Core science</span><h3>Interfaces · Defects · Ions · Transport</h3><p>I investigate how local structure and transport shape electronic-device function and reliability.</p></div><div class="home-platforms"><a href="research.html#memory"><h3>Memory &amp; reliability</h3><p>Memristive switching, state variability, and capacitive-device questions.</p></a><a href="research.html#optoelectronics"><h3>Optoelectronics &amp; hybrid devices</h3><p>Molecular contacts, photovoltaic devices, and photodetectors.</p></a><a href="research.html#flexible"><h3>Flexible &amp; stretchable electronics</h3><p>CV-listed collaborations in interconnects, stretchable PCBs, and films.</p></a></div><div class="home-future"><span>Emerging direction</span><p>Integrated &amp; 3D electronic systems</p></div></section>
  <section class="home-featured" id="featured" aria-labelledby="featured-title"><div class="shell"><div class="home-section-head"><h2 id="featured-title">Featured work</h2>${textLink('publications.html','All publications')}</div>${featured(d)}</div></section>
  <section class="home-current shell" aria-labelledby="current-title"><div class="home-section-head"><h2 id="current-title">Current research</h2>${textLink('projects.html','View all projects')}</div><div class="current-list">${previews.map(item=>{const p=d.projects.find(project=>project.id===item.id);return `<article class="current-row"><div><p class="current-category">${e(item.category)}</p><h3>${e(p.englishTitle)}</h3></div><div><p>${e(item.description)}</p><p class="current-meta">${e(p.period)} · Ongoing<br>Role: ${p.personalRole?e(p.personalRole):'<span class="verify">[VERIFY ROLE]</span>'}</p>${textLink(`projects.html#${e(item.anchor??p.id)}`,'View project')}</div></article>`}).join('')}</div></section>
  <section class="home-about shell" aria-labelledby="home-about-title"><h2 id="home-about-title">About</h2><div><p>Min Jong Lee is an integrated M.S.–Ph.D. researcher in electrical engineering at Korea University. His first-author work connects molecular interfaces, optoelectronic devices, and emerging memory.</p>${textLink('about.html','More about Min Jong Lee')}</div></section>`;
}

export function research(d) {
  const core=d.pillars.find(p=>p.id==='interfaces');
  const memory=d.pillars.find(p=>p.id==='memory');
  const future=d.pillars.find(p=>p.id==='integration');
  return `${pageHero('Research','The physics behind device behavior.','Interfaces, defects, ions, and charge transport are the common questions across my device research. Flexible-device collaborations add a mechanical dimension.')}<div class="shell research-map-wrap">${researchDiagram()}</div><div class="shell research-index"><a href="#interfaces">Core science</a><a href="#memory">Memory</a><a href="#optoelectronics">Optoelectronics</a><a href="#flexible">Flexible electronics</a><a href="#integration">Emerging direction</a></div>
  <section class="section shell research-area" id="interfaces"><div class="research-area-heading"><p class="area-type">Core science</p><h2>Interfaces, defects, ions &amp; transport</h2></div><div class="research-area-body"><h3>${e(core.question)}</h3><p>${e(core.motivation)}</p><p><strong>Established work.</strong> ${e(core.results)}</p><p><strong>Current question.</strong> ${e(core.current)}</p><p><strong>Methods.</strong> ${e(core.methods.join(' · '))}</p><p class="emerging-question"><strong>Emerging question.</strong> ${e(core.future)}</p><h4 class="small-heading">Selected publications</h4><ul class="paper-references">${core.papers.map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#optoelectronic-memory','Related projects')}${textLink('publications.html','Publications')}</div></div></section>
  <section class="section shell research-area" id="memory"><div class="research-area-heading"><p class="area-type">Device platform</p><h2>Memory &amp; reliability</h2></div><div class="research-area-body"><h3>${e(memory.question)}</h3><p>${e(memory.motivation)}</p><p><strong>Published work.</strong> ${e(memory.results)}</p><p><strong>Current focus.</strong> ${e(memory.current)}</p><p><strong>Methods.</strong> ${e(memory.methods.join(' · '))}</p><p class="emerging-question"><strong>Emerging question.</strong> ${e(memory.future)}</p><h4 class="small-heading">Selected publications</h4><ul class="paper-references">${memory.papers.map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#ionic-dynamics','Current project')}${textLink('publications.html','Publications')}</div></div></section>
  <section class="section shell research-area" id="optoelectronics"><div class="research-area-heading"><p class="area-type">Device platform</p><h2>Optoelectronics &amp; hybrid devices</h2></div><div class="research-area-body"><h3>How do contacts and traps shape light conversion and detection?</h3><p>${e(d.connected.text)}</p><p><strong>Established work.</strong> First-author papers address molecular hole-selective contacts and ALD oxide electrodes; collaborative publications span photodetectors and hybrid materials.</p><p><strong>Methods and platforms.</strong> Self-assembled monolayers · charge-selective interfaces · organic photovoltaics · photodetectors · transparent electrodes.</p><p class="emerging-question"><strong>Emerging question.</strong> How can these interface principles transfer to multifunctional optoelectronic memory?</p><h4 class="small-heading">Selected publications</h4><ul class="paper-references">${d.connected.papers.slice(0,3).map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#molecular-contacts','Related projects')}${textLink('publications.html','Publications')}</div></div></section>
  <section class="section shell research-area" id="flexible"><div class="research-area-heading"><p class="area-type">CV-listed collaborations</p><h2>${e(d.flexible.title)}</h2></div><div class="research-area-body"><h3>${e(d.flexible.question)}</h3><p>${e(d.flexible.scope)}</p><p class="record-note">${e(d.flexible.evidence)}</p><div class="research-actions">${textLink('projects.html#flexible-fpcb','Flexible interconnect project')}${textLink('projects.html#stretchable-pcb','Stretchable PCB project')}</div></div></section>
  <section class="section shell research-area research-emerging" id="integration"><div class="research-area-heading"><p class="area-type">Emerging direction</p><h2>Integrated &amp; 3D electronic systems</h2></div><div class="research-area-body"><h3>${e(future.question)}</h3><p><strong>Established foundation.</strong> ${e(future.current)}</p><p><strong>Future research.</strong> ${e(future.future)}</p><p class="record-note">Integrated and 3D systems are research directions, not completed device or circuit demonstrations in the supplied CV.</p><h4 class="small-heading">Foundation publications</h4><ul class="paper-references">${future.papers.map(id=>paperReference(d,id)).join('')}</ul><div class="research-actions">${textLink('projects.html#ald-electrodes-industry','Related projects')}${textLink('publications.html','Publications')}</div></div></section>`;
}

export function publications(d) {
  const published=d.publications.filter(p=>!p.status).sort((a,b)=>(a.type==='first'?0:1)-(b.type==='first'?0:1)||b.year-a.year);
  const manuscripts=d.publications.filter(p=>p.status);
  return `${pageHero('Publications','Published research.','Full publication records across memory, interfaces, optoelectronic and hybrid devices, and thin-film electronics.',`<div class="link-row">${textLink(d.scholar,'Google Scholar')}<button type="button" class="text-link print-button" hidden>Print publication list <span aria-hidden="true">↗</span></button></div>`)}<section class="section shell publications-section" id="publications"><h2 class="sr-only">Published papers</h2><div class="publication-controls" role="group" aria-label="Filter publications by research topic" hidden><button class="filter-button active" type="button" data-filter="all" aria-pressed="true">All</button>${d.topics.map(t=>`<button class="filter-button" type="button" data-filter="${t.id}" aria-pressed="false">${e(t.label)}</button>`).join('')}</div><div class="publication-intro"><p id="publication-count" role="status" aria-live="polite">${published.length} published papers</p><span>First-author work, followed by collaborative publications</span></div><div id="publication-list">${published.map(p=>publication(d,p)).join('')}</div><p id="publication-empty" class="publication-empty" hidden>No papers in this category are listed in the supplied CV. See <a href="projects.html#flexible-fpcb">Projects</a> for related research programs.</p><p class="record-note">${e(d.notes.authors)}</p><section class="manuscripts" aria-labelledby="manuscripts-title"><div class="section-heading"><div>${label('Work in progress')}<h2 id="manuscripts-title">Manuscripts</h2></div></div>${manuscripts.map(p=>publication(d,p)).join('')}<p class="record-note">Status as recorded in the CV updated September 2, 2026. A manuscript in revision is not an accepted or published article.</p></section><p class="record-note">${e(d.notes.bibliography)} DOI links are provided where verified; other records link to an explicitly labeled Scholar search.</p></section>`;
}

export function projects(d) {
  const byCategory=category=>d.projects.filter(p=>p.category===category);
  const independent=d.projects.find(p=>p.id==='doctoral-ionic-memory');
  const doctoral=d.researchProjects.find(p=>p.id==='ionic-dynamics');
  const publishedCases=d.researchProjects.filter(p=>p.id!=='ionic-dynamics');
  return `${pageHero('Projects','Research in practice.','Independent doctoral work, CV-listed industrial and interdisciplinary programs, and selected paper-linked device studies.')}<div class="shell projects-intro" id="projects"><p>Personal roles and outcomes are shown only where the supplied CV or linked publication record identifies them. Other roles remain marked for verification.</p></div>
  <section class="section shell project-group" id="independent"><div class="project-group-heading"><h2>Independent research</h2><p>Doctoral Research Support Program · Ministry of Education · ${e(independent.period)}</p></div>${caseStudy(d,doctoral,`<p class="original-title" lang="ko">${e(independent.title)}</p>`)}</section>
  <section class="section shell project-group" id="industry"><div class="project-group-heading"><h2>Industry collaboration</h2><p>Public project titles and sponsors from the supplied CV.</p></div><div class="program-list">${byCategory('industry').map(cvProgram).join('')}</div></section>
  <section class="section shell project-group" id="interdisciplinary"><div class="project-group-heading"><h2>Interdisciplinary programs</h2><p>Flexible materials, sensing, and photonic systems.</p></div><div class="program-list">${byCategory('interdisciplinary').map(cvProgram).join('')}</div></section>
  <section class="section shell project-group" id="collaborations"><div class="project-group-heading"><h2>Collaborative research</h2><p>CV-listed programs and paper-linked device studies.</p></div><div class="program-list">${byCategory('collaborative').map(cvProgram).join('')}</div>${publishedCases.map(p=>caseStudy(d,p)).join('')}</section><p class="record-note shell projects-note">English project labels summarize the original Korean titles. CV-listed participation does not establish a specific individual role or unpublished outcome unless stated above.</p>`;
}

export function patents(d) {
  return `${pageHero('Intellectual property','Patents &amp;<br><em>technology translation.</em>','Patent records connect materials and device research with semiconductor, memory, and optoelectronic technologies.')}<section class="section shell patent-section"><div class="section-intro"><p>Registration and application are different stages. Statuses, dates, inventors, and identifiers below follow the supplied CV.</p><p class="record-note">English labels summarize Korean titles; the original titles are retained. Related research links indicate a topic connection.</p></div><div class="patent-list">${d.patents.map((p,i)=>`<article class="patent-item" id="${p.id}"><div class="patent-number">${String(i+1).padStart(2,'0')}<span class="badge ${p.status==='Registered'?'':'badge-outline'}">${e(p.status)}</span></div><div><h2>${e(p.englishTitle)}</h2><p class="original-title" ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</p><dl class="patent-facts"><div><dt>Inventors</dt><dd lang="ko">${e(p.inventors)}</dd></div><div><dt>Jurisdiction</dt><dd>${e(p.jurisdiction)}</dd></div><div><dt>${p.status==='Registered'?'Registration number':'Application number'}</dt><dd>${e(p.number)}</dd></div><div><dt>${p.status==='Registered'?'Registration date':'Filing date'}</dt><dd>${e(p.date)}</dd></div></dl>${p.territoryNote?`<p class="record-note">${e(p.territoryNote)}</p>`:''}${tags(p.tags)}${textLink('research.html#'+p.relatedResearch,'Related research')}</div></article>`).join('')}</div></section>`;
}

export function about(d) {
  return `<section class="about-intro shell"><div class="about-intro-copy"><h1>${e(d.profile.name)}</h1><p class="about-field">Electronic Devices · Materials · Interface Physics</p><p class="about-position">Integrated M.S.–Ph.D. Researcher<br>School of Electrical Engineering<br>Korea University</p>${profiles(d)}</div>${portrait(d)}</section>
  <section class="section shell about-narrative"><div><h2>Biography</h2></div><div><p>My first-author publications span molecular contacts, organic photovoltaics, ALD oxide electrodes, optoelectronic memristors, and artificial synapses. Across these platforms, interfaces and defects are the recurring scientific questions.</p><p>My CV also lists collaborative programs in highly flexible FPCB interconnects, stretchable PCBs, and durable films. The individual roles and results for those programs are not specified in the supplied record.</p></div></section>
  <section class="section shell about-narrative"><div><h2>Research vision</h2></div><div><p>I aim to connect interface, defect, ionic, and charge-transport physics with more reliable electronic devices. My current doctoral project studies multilevel precision in ionic memory; integrated and 3D electronic systems are a longer-term research direction.</p>${textLink('research.html','Explore research')}</div></section>
  <section class="section shell about-journey"><h2>Research journey</h2><p class="section-intro">Organic and hybrid devices led to molecular interfaces, defect control, and emerging memory. Flexible-device programs run alongside this work; integrated systems remain a future direction.</p>${trajectory(d)}</section>
  <section class="section shell about-context"><div><h2>Current research environment</h2><p>${e(d.profile.lab)}<br>${e(d.profile.institution)}<br>Advisor: <a href="${e(d.profile.advisorUrl)}">${e(d.profile.advisor)}</a></p>${textLink(d.profile.labUrl,'Visit AEEL')}</div><div><h2>Education</h2><p><strong>${e(d.profile.education.degree)}</strong><br>${e(d.profile.education.school)}<br>${e(d.profile.education.period)}</p><p class="about-independence">The supplied CV identifies Min Jong Lee as principal investigator of the doctoral research support project begun in September 2026.</p>${textLink('projects.html#independent','Independent research')}</div></section>${activities(d)}`;
}

export function activities(d) {
  const list=category=>d.awards.filter(a=>a.category===category).sort((a,b)=>b.year-a.year).map(a=>`<article class="activity-row"><span class="period">${a.year}</span><div><h3>${e(a.englishTitle)}</h3><p lang="ko">${e(a.title)}</p></div></article>`).join('');
  return `<section class="section shell about-recognition" id="recognition"><h2>Selected awards &amp; recognition</h2><div class="activity-list">${list('award')}</div><h3 class="recognition-subhead">Scholarships &amp; researcher programs</h3><div class="activity-list">${list('fellowship')}</div><p class="record-note">Records follow the CV updated ${e(d.profile.updated)}. English labels are descriptive translations of the Korean titles.</p></section><section class="section shell about-gallery" id="gallery"><h2>Research / conference gallery</h2>${d.gallery.some(g=>g.image)?`<div class="gallery-grid">${d.gallery.filter(g=>g.image).map(g=>`<figure><div class="gallery-image"><img src="${e(g.image)}" alt="${e(g.alt)}" width="900" height="675" loading="lazy" decoding="async"></div><figcaption><h3>${e(g.title)}</h3><p>${e(g.caption)}</p></figcaption></figure>`).join('')}</div>`:'<p class="record-note">[ADD REPRESENTATIVE IMAGE]</p>'}</section>`;
}

export function cv(d) {
  const pubs=d.publications.filter(p=>!p.status).sort((a,b)=>b.year-a.year);
  return `<div class="shell cv-toolbar">${textLink(d.profile.cv,'Download CV (PDF)','download')}<button class="text-link print-button" type="button" hidden>Print CV <span aria-hidden="true">↗</span></button><span>Public version · Record updated ${e(d.profile.updated)}</span></div><article class="cv-document shell"><header><p class="eyebrow">Curriculum vitae</p><h1>Min Jong Lee</h1><p>School of Electrical Engineering, Korea University<br>Seoul, Republic of Korea · <a href="mailto:${e(d.profile.email)}">${e(d.profile.email)}</a><br><a href="https://minjonglee.github.io/">minjonglee.github.io</a> · <a href="${e(d.scholar)}">Google Scholar</a></p></header><section><h2>Research identity</h2><p>Interface and device physics for emerging electronics</p><p>Research interests: molecular and thin-film interfaces, defects, ionic dynamics, charge transport, emerging memory, optoelectronics, and flexible-device collaborations. Integrated and 3D electronics is a future research direction.</p></section><section><h2>Education</h2><p><strong>${e(d.profile.education.degree)}</strong> · ${e(d.profile.education.period)}<br>${e(d.profile.education.school)}<br>Advisor: ${e(d.profile.advisor)}</p></section><section><h2>Publications</h2><ol class="cv-publications">${pubs.map(p=>`<li><p>${authors(p.authors)}. “${e(p.title)}.” <em>${e(p.journal)}</em> (${p.year}).${p.type==='first'?' <strong>[First author]</strong>':''}${p.doi?` <a href="https://doi.org/${e(p.doi)}">doi:${e(p.doi)}</a>`:''}</p></li>`).join('')}</ol></section><section><h2>Manuscript in revision</h2>${d.publications.filter(p=>p.status).map(p=>`<p>${authors(p.authors)}. “${e(p.title)}.” ${e(p.journal)} (${p.year}). <strong>${e(p.status)}; not published.</strong></p>`).join('')}</section><section><h2>Patents</h2><ol>${d.patents.map(p=>`<li><p><span lang="ko">${e(p.inventors)}</span>. “<span ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</span>.” ${e(p.status)} · ${e(p.jurisdiction)} · ${e(p.number)} · ${e(p.date)}.${p.territoryNote?' '+e(p.territoryNote):''}</p></li>`).join('')}</ol></section><section><h2>Research projects</h2>${d.projects.map(p=>`<div class="cv-entry"><p><strong>${e(p.englishTitle)}</strong><br><span lang="ko">${e(p.title)}</span><br>${e(p.sponsor)} · ${e(p.period)}${p.personalRole?' · '+e(p.personalRole):''}</p></div>`).join('')}</section><section><h2>Awards &amp; academic programs</h2>${d.awards.map(a=>`<div class="cv-entry"><p><strong>${a.year} · ${e(a.englishTitle)}</strong><br><span lang="ko">${e(a.title)}</span></p></div>`).join('')}</section><p class="cv-source">Public CV adapted from the record updated ${e(d.profile.updated)}. English labels for Korean project and award titles are descriptive translations. † Equal contribution; * Corresponding author. Original phone number and detailed postal address omitted.</p></article>`;
}
