import {escape as e, textLink, paperLink, isPublicationVisible, isUnpublished, label, profiles, portrait, scientificVisual, researchDiagram, trajectory, paperReference, publication, featured, pageHero, authors, formatPeriod, sectionTabs, patentIdentifier, patentRecordDate} from './components.mjs';

const cvProgram = p => `<article class="program-row" id="${e(p.id)}"><div><p class="program-label">${e(p.program||p.category)} · ${e(p.status||'')}</p><h3>${e(p.englishTitle)}</h3><p class="original-title" lang="ko">${e(p.title)}</p></div><div class="program-detail"><p class="program-meta">${e(p.fundingAgency||p.sponsor)} · ${e(formatPeriod(p.period))}</p><p class="program-role">Role: ${e(p.personalRole)}</p>${p.personalParticipationPeriod?`<p>My participation: ${e(formatPeriod(p.personalParticipationPeriod))}</p>`:''}${p.summary?`<p class="program-summary">${e(p.summary)}</p>`:''}${p.externalUrl?textLink(p.externalUrl,'Project link'):''}</div></article>`;
const caseStudy = (d,p) => `<article class="project-detail" id="${e(p.id)}"><div class="project-heading"><p class="project-state">${e(p.status)}</p><h3>${e(p.title)}</h3></div><div class="project-body"><p class="research-question">${e(p.question)}</p><dl class="project-facts"><div><dt>Role</dt><dd>${e(p.role)}</dd></div><div><dt>Scientific approach</dt><dd>${e(p.approach)}</dd></div><div><dt>${(p.papers??[]).length?'Key finding':'Current status'}</dt><dd>${e(p.outcome)}</dd></div></dl>${(p.papers??[]).length?`<h4 class="small-heading">Related publications</h4><ul class="paper-references">${p.papers.map(id=>paperReference(d,id)).join('')}</ul>`:''}${(p.patents??[]).length?`<h4 class="small-heading">Related patents</h4><ul class="paper-references">${p.patents.map(id=>{const patent=d.patents.find(item=>item.id===id);return patent?`<li><a href="patents.html#${e(patent.id)}">${e(patent.englishTitle)}</a><span>${e(patent.status)} · ${e(patentIdentifier(patent))}</span></li>`:''}).join('')}</ul>`:''}</div></article>`;

const richLinks=links=>(links??[]).map(link=>textLink(link.href,link.label)).join('');
const heroFrom=data=>pageHero(e(data.hero.kicker),e(data.hero.title),e(data.hero.description));
const publicationsTabs=file=>sectionTabs([{label:'Papers',href:'publications.html'},{label:'Patents',href:'patents.html'},{label:'Conferences',href:'conferences.html'}],file,'Publications sections');
const researchTabs=file=>sectionTabs([{label:'Overview',href:'research.html'},{label:'Projects',href:'projects.html'}],file,'Research sections');
const outputHero=(title,description)=>`<header class="shell publications-hero"><h1>${e(title)}</h1><p>${e(description)}</p></header>`;
const projectAnchor=(d,p)=>{
  const caseId=p.caseStudyId&&d.researchProjects.some(item=>item.id===p.caseStudyId)?p.caseStudyId:null;
  return caseId?(p.homeAnchor||caseId):p.id;
};

export function home(d) {
  const page=d.pages.home, h=page.hero;
  const core=d.research.find(item=>item.homeRole==='core'&&item.featured);
  const platforms=d.research.filter(item=>item.homeRole==='platform'&&item.featured);
  const future=d.research.find(item=>item.homeRole==='future'&&item.featured);
  const latest=d.news.filter(item=>item.featured).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,2);
  return `<section class="home-hero shell"><div class="home-hero-grid"><div class="home-hero-copy"><p class="home-name">${e(d.profile.name.toUpperCase())}</p><h1>${e(h.line1)}<br>${e(h.line2Prefix)}<span class="accent-phrase">${e(h.accent)}</span></h1><p class="home-deck">${e(h.deck)}</p><dl class="hero-focus"><div><dt>${e(h.focusCurrentLabel)}</dt><dd>${e(h.focusCurrent)}</dd></div><div><dt>${e(h.focusFutureLabel)}</dt><dd>${e(h.focusFuture)}</dd></div></dl><p class="home-affiliation">${e(h.affiliation)}</p><div class="home-actions">${h.actions.map(action=>`<a class="text-link" href="${e(action.kind==='cv'?d.profile.cv:action.href)}"${action.kind==='cv'?' download':''}>${e(action.label)} <span aria-hidden="true">${e(action.arrow)}</span></a>`).join('')}</div></div>${scientificVisual(d.profile.heroImage,d.profile.heroImageAlt,{label:d.profile.heroImageCaption??'Research figure',className:'hero-science'})}</div></section>
  <section class="home-research shell" id="research" aria-labelledby="home-research-title"><div class="home-section-head"><h2 id="home-research-title">${e(page.research.title)}</h2>${textLink('research.html',e(page.research.moreLabel))}</div>${core?`<div class="home-core"><span>${e(page.research.coreLabel)}</span><h3>${e(core.homeTitle)}</h3><p>${e(core.homeDescription)}</p></div>`:''}<div class="home-platforms">${platforms.map(item=>`<a href="research.html#${e(item.id)}"><h3>${e(item.homeTitle)}</h3><p>${e(item.homeDescription)}</p></a>`).join('')}</div>${future?`<div class="home-future"><span>${e(page.research.futureLabel)}</span><p>${e(future.homeTitle)}</p><small>${e(future.homeDescription)}</small></div>`:''}</section>
  <section class="home-featured" id="featured" aria-labelledby="featured-title"><div class="shell"><div class="home-section-head"><h2 id="featured-title">${e(page.featured.title)}</h2>${textLink('publications.html',e(page.featured.moreLabel))}</div>${featured(d)}</div></section>
  <section class="home-activities shell" aria-labelledby="home-activities-title"><div class="home-section-head"><h2 id="home-activities-title">${e(page.activities.title)}</h2>${textLink('activities.html',e(page.activities.moreLabel))}</div>${latest.length?`<div class="home-activity-list">${latest.map(item=>`<article><p>${e(item.date||'')} · ${e(item.source||item.type||'')}</p><h3>${item.url?`<a href="${e(item.url)}">${e(item.title)}</a>`:e(item.title)}</h3></article>`).join('')}</div>`:`<p class="home-activity-empty">${e(page.activities.empty)}</p>`}</section>`;
}

export function research(d) {
  const page=d.pages.research;
  return `${heroFrom(page)}${researchTabs('research.html')}<div class="shell research-map-wrap">${researchDiagram(page.map)}</div>
  ${d.research.map(area=>`<section class="section shell research-area${area.prospective?' research-emerging':''}" id="${e(area.id)}"><div class="research-area-heading"><p class="area-type">${e(area.areaType)}</p><h2>${e(area.displayTitle)}</h2>${area.image?scientificVisual(area.image,area.alt,{label:area.caption??'Research figure',className:'research-science'}):''}</div><div class="research-area-body"><h3>${e(area.question)}</h3>${(area.paragraphs??[]).map(p=>`<p>${p.label?`<strong>${e(p.label)}</strong> `:''}${e(p.text)}</p>`).join('')}${area.showPapers&&area.selectedPapers?.length?`<h4 class="small-heading">${e(page.selectedPapersHeading)}</h4><ul class="paper-references">${area.selectedPapers.map(id=>paperReference(d,id)).join('')}</ul>`:''}<div class="research-actions">${richLinks(area.links)}</div></div></section>`).join('')}`;
}

export function publications(d) {
  const page=d.pages.publications;
  const byDate=(a,b)=>Number(b.year)-Number(a.year)||String(b.publicationDate||b.onlinePublicationDate||'').localeCompare(String(a.publicationDate||a.onlinePublicationDate||''))||Number(a.order??999)-Number(b.order??999);
  const published=d.publications.filter(isPublicationVisible).sort(byDate);
  const years=[...new Set(published.map(p=>p.year))];
  const allYears=[...new Set(published.map(p=>p.year))].sort((a,b)=>b-a);
  return `${outputHero(page.hero.title,page.hero.description)}${publicationsTabs('publications.html')}
  <section class="shell publications-section" id="publications" aria-label="Publication list"><div class="publication-controls"><label class="sr-only" for="publication-search">Search publications</label><input id="publication-search" type="search" placeholder="Search title, author, journal or year" autocomplete="off"><label class="sr-only" for="publication-year-filter">Filter by year</label><select id="publication-year-filter"><option value="all">All years</option>${allYears.map(year=>`<option value="${e(year)}">${e(year)}</option>`).join('')}</select></div><p class="publication-count" id="publication-count" role="status" aria-live="polite">${published.length} publications</p><div id="publication-list">${years.map(year=>`<section class="publication-year" data-year-group><h2>${e(year)}</h2>${published.filter(p=>p.year===year).map(p=>publication(d,p)).join('')}</section>`).join('')}</div><p id="publication-empty" class="publication-empty" hidden>No publications match this search and year.</p><p class="record-note">${e(d.notes.authors)}</p></section>`;
}

export function projects(d) {
  const page=d.pages.projects;
  return `${heroFrom(page)}${researchTabs('projects.html')}${page.groups.map(group=>{const programs=d.projects.filter(p=>p.category===group.id);return `<section class="section shell project-group" id="${e(group.id)}"><div class="project-group-heading"><h2>${e(group.title.replace(/^\d+ · /,''))}</h2>${group.description?`<p>${e(group.description)}</p>`:''}</div><div class="program-list">${programs.map(cvProgram).join('')}</div></section>`}).join('')}<section class="section shell project-cases"><h2>Research case studies</h2><div class="project-case-list">${d.researchProjects.map(p=>caseStudy(d,p)).join('')}</div></section><div class="shell project-endnote"><p class="record-note">${e(page.note)}</p>${textLink(page.outputsUrl,e(page.outputsLabel))}</div>`;
}

export function patents(d) {
  const page=d.pages.patents;
  const ordered=[...d.patents].sort((a,b)=>String(patentRecordDate(b)).localeCompare(String(patentRecordDate(a)))||Number(a.order??999)-Number(b.order??999));
  const years=[...new Set(ordered.map(p=>String(patentRecordDate(p)).slice(0,4)))];
  const entry=p=>{
    const registered=['Registered','Granted'].includes(p.status);
    const date=patentRecordDate(p).replaceAll('-','.');
    const jurisdiction=p.jurisdiction||({KR:'Korea',US:'United States'}[p.country]||p.country);
    const facts=[
      date||jurisdiction?`<div><dt>${registered?'Registration':'Application'}</dt><dd>${e([jurisdiction,date].filter(Boolean).join(' · '))}</dd></div>`:'',
      p.registrationNumber?`<div><dt>Registration No.</dt><dd>${e(p.registrationNumber)}</dd></div>`:'',
      p.applicationNumber?`<div><dt>Application No.</dt><dd>${e(p.applicationNumber)}</dd></div>`:'',
      p.assignee?`<div><dt>Assignee</dt><dd>${e(p.assignee)}</dd></div>`:''
    ].join('');
    return `<article class="output-entry patent-entry" id="${e(p.id)}" data-patent-status="${registered?'registered':'application'}"><span class="output-badge">${e(registered?'Registered':p.status==='Application'?'Application':p.status)}</span><h3 class="output-title" ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</h3><p class="output-authors" lang="ko">${e(p.inventors)}</p>${facts?`<dl class="output-facts">${facts}</dl>`:''}${p.territoryNote?`<p class="record-note">${e(p.territoryNote)}</p>`:''}${p.description?`<p class="output-description">${e(p.description)}</p>`:''}${p.externalUrl?textLink(p.externalUrl,'Patent record'):''}</article>`;
  };
  return `${outputHero('Patents',page.hero.description)}${publicationsTabs('patents.html')}<section class="shell output-section"><div class="patent-filters" role="group" aria-label="Filter patents by status"><button type="button" data-patent-filter="all" aria-pressed="true">All</button><button type="button" data-patent-filter="registered" aria-pressed="false">Registered</button><button type="button" data-patent-filter="application" aria-pressed="false">Application</button></div>${years.map(year=>`<section class="output-year patent-year" data-patent-year><h2>${e(year)}</h2>${ordered.filter(p=>String(patentRecordDate(p)).startsWith(year)).map(entry).join('')}</section>`).join('')}<p class="output-empty" id="patent-empty" hidden>No patents match this filter.</p><p class="record-note">${e(page.intro)}</p></section>`;
}

export function conferences(d) {
  const page=d.pages.conferences;
  const ordered=[...d.conferences].sort((a,b)=>Number(b.year)-Number(a.year)||String(b.date||'').localeCompare(String(a.date||''))||Number(a.order??999)-Number(b.order??999));
  const years=[...new Set(ordered.map(item=>item.year))];
  const entry=item=>`<article class="output-entry conference-entry" id="${e(item.id)}">${item.title?`<p class="output-source">${e(item.conferenceName)}</p><h3 class="output-title">${e(item.title)}</h3>`:`<h3 class="output-title">${e(item.conferenceName)}</h3>`}${item.authors?`<p class="output-authors">${authors(item.authors)}</p>`:''}<div class="conference-details">${item.presentationType?`<span class="output-badge">${e(item.presentationType)}</span>`:''}${item.date?`<span>${e(item.date)}</span>`:''}${item.location?`<span>${e(item.location)}</span>`:''}</div>${item.description?`<p class="output-description">${e(item.description)}</p>`:''}${item.url?textLink(item.url,'Conference record'):''}</article>`;
  return `${outputHero(page.hero.title,page.hero.description)}${publicationsTabs('conferences.html')}<section class="shell output-section">${years.length?years.map(year=>`<section class="output-year"><h2>${e(year)}</h2>${ordered.filter(item=>item.year===year).map(entry).join('')}</section>`).join(''):`<p class="output-empty">${e(page.empty)}</p>`}</section>`;
}

export function about(d) {
  const page=d.pages.about;
  const education=d.education.map(item=>{const [university,...location]=item.school.split(', ');const details=[item.gpa?`GPA: ${e(item.gpa)}`:'',item.honor?e(item.honor):''].filter(Boolean).join(' · ');return `<article class="education-entry"><p class="education-period">${e(item.period||'')}</p><p><strong>${e(item.degree)}</strong><br>${e(university)}${location.length?`<br>${e(location.join(', '))}`:''}</p>${details||item.advisor?`<p class="education-meta">${details}${item.advisor?`${details?'<br>':''}Advisor: ${e(item.advisor)}`:''}</p>`:''}</article>`}).join('');
  const experience=d.experience.map(item=>`<article class="education-entry"><p class="education-period">${e(item.period)}</p><p><strong>${e(item.title)}</strong><br>${e(item.department)}<br>${e(item.organization)}</p>${item.description?`<p>${e(item.description)}</p>`:''}</article>`).join('');
  const awards=[...d.awards].sort((a,b)=>Number(b.year)-Number(a.year)||Number(a.order??999)-Number(b.order??999));
  const years=[...new Set(awards.map(item=>item.year))];
  return `<section class="about-intro shell"><div class="about-intro-copy"><h1>${e(d.profile.name)}</h1><p class="about-field">${e(page.field)}</p><p class="about-position">${page.positionLines.map(e).join('<br>')}</p>${profiles(d)}</div>${portrait(d)}</section>
  <section class="section shell about-narrative" id="profile"><div><h2>${e(page.biographyTitle)}</h2></div><div><p>${e(d.profile.bio)}</p><p>${e(page.biographyExtra)}</p></div></section>
  <section class="section shell about-narrative"><div><h2>${e(page.visionTitle)}</h2></div><div><p>${e(d.profile.vision)}</p>${textLink('research.html',e(page.visionLinkLabel))}</div></section>
  <section class="section shell about-journey"><h2>${e(page.journeyTitle)}</h2><p class="section-intro">${e(page.journeyIntro)}</p>${trajectory(d)}</section>
  <section class="section shell about-context"><div><h2>${e(page.environmentTitle)}</h2><p>${e(d.profile.lab)}<br>${e(d.profile.institution)}<br>Advisor: <a href="${e(d.profile.advisorUrl)}">${e(d.profile.advisor)}</a></p><p class="about-independence">${e(page.independence)}</p>${textLink('projects.html#independent',e(page.independentLinkLabel))}${textLink(d.profile.labUrl,e(page.labLinkLabel))}</div><div><h2>Academic profile</h2><p>${e(d.profile.position)}<br>${e(d.profile.department)}<br>${e(d.profile.institution)}</p></div></section>
  <section class="section shell about-records"><div id="education"><h2>${e(page.educationTitle)}</h2>${education}</div><div id="experience"><h2>Experience</h2>${experience}</div></section>
  <section class="section shell about-recognition" id="recognition"><h2>Honors &amp; Scholarships</h2>${years.map(year=>`<div class="award-year"><h3>${e(year)}</h3>${awards.filter(item=>item.year===year).map(item=>`<article class="award-entry"><span class="award-type">${e(item.type)}</span><h4>${e(item.title)}</h4>${item.organization?`<p>${e(item.organization)}</p>`:''}${item.description?`<p>${e(item.description)}</p>`:''}${item.url?textLink(item.url,'Award record'):''}</article>`).join('')}</div>`).join('')}</section>
  <section class="section shell about-activities"><div><h2>${e(page.activitiesTitle)}</h2><p>${e(page.activitiesIntro)}</p></div>${textLink('activities.html',e(page.activitiesLinkLabel))}</section>`;
}

export function activities(d) {
  const page=d.pages.activities;
  const news=[...d.news].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||Number(a.order??999)-Number(b.order??999));
  const photos=d.gallery.filter(item=>item.image);
  const gallery=photos.length
    ? `<div class="gallery-grid">${photos.map((item,i)=>`<figure class="gallery-item"><button type="button" class="gallery-open" data-gallery-index="${i}" data-gallery-title="${e(item.title)}" data-gallery-category="${e(item.category)}" data-gallery-location="${e(item.location??'')}" data-gallery-year="${e(item.year??'')}" data-gallery-caption="${e(item.caption??'')}" aria-label="Open image: ${e(item.title)}"><img src="${e(item.image)}" alt="${e(item.alt)}" width="900" height="675" loading="lazy" decoding="async"></button><figcaption><p class="gallery-category">${e(item.category)}</p><h3>${e(item.title)}</h3><p>${e([item.location,item.year].filter(Boolean).join(' · '))}</p>${item.caption?`<p>${e(item.caption)}</p>`:''}</figcaption></figure>`).join('')}</div><dialog class="gallery-dialog" id="gallery-dialog" aria-label="Gallery image"><div class="gallery-dialog-inner"><button type="button" class="gallery-close" aria-label="Close image">Close ×</button><img alt=""><div class="gallery-dialog-copy"><p class="gallery-dialog-meta"></p><h2 class="gallery-dialog-title"></h2><p class="gallery-dialog-caption"></p><div class="gallery-dialog-controls"><button type="button" class="gallery-prev">← Previous</button><button type="button" class="gallery-next">Next →</button></div></div></div></dialog>`
    : `<p class="output-empty">${e(page.galleryEmpty)}</p>`;
  return `${heroFrom(page)}<section class="section shell activities-news" id="news"><div class="section-heading"><div><h2>News &amp; Media</h2><p class="section-intro">${e(page.newsIntro)}</p></div></div>${news.length?`<div class="news-list">${news.map(item=>`<article class="news-item${item.featured?' news-featured':''}" id="${e(item.id)}">${item.thumbnail?`<img src="${e(item.thumbnail)}" alt="${e(item.thumbnailAlt||item.title)}" width="640" height="400" loading="lazy" decoding="async">`:''}<div><p class="news-meta">${e([item.date,item.source||item.type].filter(Boolean).join(' · '))}</p><h3>${item.url?`<a href="${e(item.url)}">${e(item.title)}</a>`:e(item.title)}</h3>${item.shortDescription?`<p>${e(item.shortDescription)}</p>`:''}</div></article>`).join('')}</div>`:`<p class="output-empty">${e(page.newsEmpty)}</p>`}</section><section class="section shell activities-gallery" id="gallery"><div class="section-heading"><div><h2>${e(page.galleryTitle)}</h2><p class="section-intro">${e(page.galleryIntro)}</p></div></div>${gallery}</section>`;
}

export function cv(d) {
  const page=d.pages.cv;
  const pubs=d.publications.filter(p=>!isUnpublished(p)).sort((a,b)=>b.year-a.year);
  const education=d.education.map(item=>`<p><strong>${e(item.degree)}</strong> · ${e(item.period||'')}<br>${e(item.school)}${item.gpa?`<br>GPA: ${e(item.gpa)}`:''}${item.honor?` · ${e(item.honor)}`:''}${item.advisor?`<br>Advisor: ${e(item.advisor)}`:''}</p>`).join('');
  return `<div class="shell cv-toolbar">${textLink(d.profile.cv,e(page.downloadLabel),'download')}<button class="text-link print-button" type="button" hidden>Print CV <span aria-hidden="true">↗</span></button><span>${e(page.updatedPrefix)} ${e(d.profile.updated)}</span></div><article class="cv-document shell"><header><p class="eyebrow">Curriculum vitae</p><h1>${e(d.profile.name)}</h1><p>${e(d.profile.department)}, ${e(d.profile.institution)}<br>${e(d.profile.location)} · <a href="mailto:${e(d.profile.email)}">${e(d.profile.email)}</a><br><a href="${e(d.site.baseUrl)}">${e(new URL(d.site.baseUrl).hostname)}</a> · <a href="${e(d.scholar)}">Google Scholar</a></p></header><section><h2>${e(page.researchIdentityTitle)}</h2><p>${e(page.researchIdentity)}</p><p>${e(page.researchInterests)}</p></section><section><h2>Education</h2>${education}</section><section><h2>Publications</h2><ol class="cv-publications">${pubs.map(p=>`<li><p>${authors(p.authors)}. “${e(p.title)}.” <em>${e(p.journalName||p.journal)}</em> (${p.year}).${p.type==='first'||p.firstAuthor?' <strong>[First author]</strong>':''}${p.doi?` <a href="https://doi.org/${e(p.doi)}">doi:${e(p.doi)}</a>`:''}</p></li>`).join('')}</ol></section><section><h2>Patents</h2><ol>${d.patents.map(p=>`<li><p><span lang="ko">${e(p.inventors)}</span>. “<span ${/[가-힣]/.test(p.title)?'lang="ko"':''}>${e(p.title)}</span>.” ${e(p.status)} · ${e(p.jurisdiction)} · ${p.numberLabel?`${e(p.numberLabel)}: `:''}${e(patentIdentifier(p))} · ${e(patentRecordDate(p))}.${p.territoryNote?' '+e(p.territoryNote):''}</p></li>`).join('')}</ol></section><section><h2>Research projects</h2>${d.projects.map(p=>`<div class="cv-entry"><p><strong>${e(p.englishTitle)}</strong><br><span lang="ko">${e(p.title)}</span><br>${e(p.sponsor)}<br>Program period: ${e(formatPeriod(p.period))} · Role: ${e(p.personalRole)}${p.personalParticipationPeriod?`<br>My participation: ${e(formatPeriod(p.personalParticipationPeriod))}`:''}</p></div>`).join('')}</section><section><h2>Awards &amp; academic programs</h2>${d.awards.map(a=>`<div class="cv-entry"><p><strong>${a.year} · ${e(a.englishTitle)}</strong><br><span lang="ko">${e(a.title)}</span></p></div>`).join('')}</section><p class="cv-source">${e(page.sourceNote)}</p></article>`;
}
